### ISSUE TITLE
plugin has a bad effect on the openpifpaf detector? 

### ISSUE THREAD

**Issue by chaserat** [vita-epfl/openpifpaf_posetrack#2]
The contrast test is based on openpifpaf-0.11.9, which in the crowd scene, hardly to find the wrong matches body keypoints. While the test based on openpifpaf-0.12.5 with posetrack-0.3.0 plugin, while in crowd scene(27 persons ), some upper bodies matches the wrong lower bodies.
Needless to say, the test are both based on the shuffflenetv2 model. 
![image](https://user-images.githubusercontent.com/30485904/111251420-26b48a00-864a-11eb-82ea-226ffb593c6c.png)

**Comment by svenkreiss** [comment]
Thanks @chaserat . What you are seeing is a tracking error. The persons were overlapping in a previous frame. Are you running with the default parameterization or did you reduce keypoint thresholds or ran with `--force-complete-pose`?
Alternatively, try to increase `--caf-th`.

With our latest models and configurations, we haven't seen this type of tracking error in a while. Can you share the video sequence so that we can use it to improve?

**Comment by chaserat** [comment]
Thanks for your patient. I'm sorry to reply so late. The Data I'm not sure it is OK to share, Later, I will look for some similar scene to locate the same problem and share the new video with you.

**Comment by svenkreiss** [comment]
Thanks @chaserat . I'll close this for now but feel free to reopen when you have more info.
